# I. Import libraries 

In [1]:
import pandas as pd
import numpy as np
import collections.abc  as carr

# II. EDA

In [2]:
initial_df :carr.MutableSequence[float] = pd.read_csv("updated_pollution_dataset.csv")
initial_df.loc[:,"Temperature"]

m,n= initial_df.shape

In [3]:
print("m:",m,"n:",n)

m: 5000 n: 10


In [4]:
initial_df.iloc[:3,:]

Temperature  Humidity  PM2.5  PM10   NO2   SO2    CO  \
0         29.8      59.1    5.2  17.9  18.9   9.2  1.72   
1         28.3      75.6    2.3  12.2  30.8   9.7  1.64   
2         23.1      74.7   26.7  33.8  24.4  12.6  1.63   

   Proximity_to_Industrial_Areas  Population_Density Air Quality  
0                            6.3                 319    Moderate  
1                            6.0                 611    Moderate  
2                            5.2                 619    Moderate

In [5]:
initial_df.iloc[3:11,:]

Temperature  Humidity  PM2.5  PM10   NO2   SO2    CO  \
3          27.1      39.1    6.1   6.3  13.5   5.3  1.15   
4          26.5      70.7    6.9  16.0  21.9   5.6  1.01   
5          39.4      96.6   14.6  35.5  42.9  17.9  1.82   
6          41.7      82.5    1.7  15.8  31.1  12.7  1.80   
7          31.0      59.6    5.0  16.8  24.2  13.6  1.38   
8          29.4      93.8   10.3  22.7  45.1  11.8  2.03   
9          33.2      80.5   11.1  24.4  32.0  15.3  1.69   
10         26.3      65.7    1.3   5.5  18.3   5.9  0.85   

    Proximity_to_Industrial_Areas  Population_Density Air Quality  
3                            11.1                 551        Good  
4                            12.7                 303        Good  
5                             3.1                 674   Hazardous  
6                             4.6                 735        Poor  
7                             6.3                 443    Moderate  
8                             5.4                 486        Poor  
9                             4.9                 535        Poor  
10                           13.0                 529        Good

In [6]:
# EDA
num_initial_col_df = len(initial_df.columns)
describe_initial_df = initial_df.describe()
num_na_initial_df = initial_df.isna().sum()
combined_data = [["# of variables","data stats","# of Na"],[num_initial_col_df,describe_initial_df,num_na_initial_df]]
for desc, data in zip(combined_data[0],combined_data[1]):
    print(desc + ":\n", data)

# of variables:
 10
data stats:
        Temperature     Humidity        PM2.5         PM10          NO2  \
count  5000.000000  5000.000000  5000.000000  5000.000000  5000.000000   
mean     30.029020    70.056120    20.142140    30.218360    26.412100   
std       6.720661    15.863577    24.554546    27.349199     8.895356   
min      13.400000    36.000000     0.000000    -0.200000     7.400000   
25%      25.100000    58.300000     4.600000    12.300000    20.100000   
50%      29.000000    69.800000    12.000000    21.700000    25.300000   
75%      34.000000    80.300000    26.100000    38.100000    31.900000   
max      58.600000   128.100000   295.000000   315.800000    64.900000   

               SO2           CO  Proximity_to_Industrial_Areas  \
count  5000.000000  5000.000000                    5000.000000   
mean     10.014820     1.500354                       8.425400   
std       6.750303     0.546027                       3.610944   
min      -6.200000     0.650000     

## notes from data 
- based from the data given above, the values has very large in which necitates normalization
- the target variable is air quality as it is the one that is optimal to integer type categorization

# III. Data Transformation

In [7]:
# create copy
categorized_df = initial_df.copy(deep= True)



In [8]:
# data normalization and removing the target column (variable)
df_normalized = categorized_df.iloc[:,:9].transform(lambda x: (x - x.min())/ (x.max() - x.min()))
df_normalized

Temperature  Humidity     PM2.5      PM10       NO2       SO2        CO  \
0        0.362832  0.250814  0.017627  0.057278  0.200000  0.301370  0.348534   
1        0.329646  0.429967  0.007797  0.039241  0.406957  0.311155  0.322476   
2        0.214602  0.420195  0.090508  0.107595  0.295652  0.367906  0.319218   
3        0.303097  0.033659  0.020678  0.020570  0.106087  0.225049  0.162866   
4        0.289823  0.376764  0.023390  0.051266  0.252174  0.230920  0.117264   
...           ...       ...       ...       ...       ...       ...       ...   
4995     0.601770  0.413681  0.393220  0.401582  0.662609  0.624266  0.475570   
4996     0.325221  0.661238  0.023390  0.079747  0.311304  0.332681  0.289902   
4997     0.276549  0.458198  0.048136  0.070570  0.476522  0.273973  0.319218   
4998     0.263274  0.091205  0.072542  0.092405  0.283478  0.232877  0.078176   
4999     0.236726  0.454940  0.276949  0.299051  0.274783  0.326810  0.237785   

      Proximity_to_Industrial_Areas  Population_Density  
0                          0.163090            0.170351  
1                          0.150215            0.550065  
2                          0.115880            0.560468  
3                          0.369099            0.472042  
4                          0.437768            0.149545  
...                             ...                 ...  
4995                       0.012876            0.750325  
4996                       0.137339            0.677503  
4997                       0.304721            0.248375  
4998                       0.390558            0.068921  
4999                       0.248927            0.355007  

[5000 rows x 9 columns]

In [9]:
# data mean normalization
df_mean_norm = categorized_df.iloc[:,:9].transform(lambda x: (x - x.mean())/ (x.std()))
df_mean_norm

Temperature  Humidity     PM2.5      PM10       NO2       SO2        CO  \
0       -0.034077 -0.690646 -0.608528 -0.450410 -0.844497 -0.120709  0.402262   
1       -0.257269  0.349472 -0.726633 -0.658826  0.493280 -0.046638  0.255749   
2       -1.031003  0.292739  0.267073  0.130960 -0.226197  0.382972  0.237435   
3       -0.435823 -1.951396 -0.571875 -0.874554 -1.451555 -0.698460 -0.641643   
4       -0.525100  0.040589 -0.539295 -0.519882 -0.507242 -0.654018 -0.898040   
...           ...       ...       ...       ...       ...       ...       ...   
4995     1.572908  0.254916  3.903874  3.527768  2.145827  2.323626  1.116513   
4996    -0.287028  1.692171 -0.539295 -0.190805 -0.125020  0.116318  0.072608   
4997    -0.614377  0.513370 -0.241998 -0.296841  0.942953 -0.328107  0.237435   
4998    -0.703654 -1.617297  0.051227 -0.044548 -0.304889 -0.639204 -1.117810   
4999    -0.882208  0.494458  2.506984  2.343090 -0.361099  0.071875 -0.220418   

      Proximity_to_Industrial_Areas  Population_Density  
0                         -0.588600           -1.168046  
1                         -0.671680            0.743523  
2                         -0.893229            0.795895  
3                          0.740693            0.350735  
4                          1.183790           -1.272790  
...                             ...                 ...  
4995                      -1.557875            1.751680  
4996                      -0.754761            1.385077  
4997                       0.325289           -0.775258  
4998                       0.879161           -1.678671  
4999                      -0.034728           -0.238447  

[5000 rows x 9 columns]

In [10]:
# categorizing the target variable and concat in two types of normalization
Air_quality_cat = initial_df.loc[:,"Air Quality"]
categorized_df_y = pd.Categorical(Air_quality_cat)
df_normalized.loc[:,"Air Quality"] = categorized_df_y.codes
df_mean_norm.loc[:,"Air Quality"] = categorized_df_y.codes

In [11]:
categorized_df_y

['Moderate', 'Moderate', 'Moderate', 'Good', 'Good', ..., 'Hazardous', 'Moderate', 'Moderate', 'Good', 'Moderate']
Length: 5000
Categories (4, object): ['Good', 'Hazardous', 'Moderate', 'Poor']

In [12]:
df_normalized

Temperature  Humidity     PM2.5      PM10       NO2       SO2        CO  \
0        0.362832  0.250814  0.017627  0.057278  0.200000  0.301370  0.348534   
1        0.329646  0.429967  0.007797  0.039241  0.406957  0.311155  0.322476   
2        0.214602  0.420195  0.090508  0.107595  0.295652  0.367906  0.319218   
3        0.303097  0.033659  0.020678  0.020570  0.106087  0.225049  0.162866   
4        0.289823  0.376764  0.023390  0.051266  0.252174  0.230920  0.117264   
...           ...       ...       ...       ...       ...       ...       ...   
4995     0.601770  0.413681  0.393220  0.401582  0.662609  0.624266  0.475570   
4996     0.325221  0.661238  0.023390  0.079747  0.311304  0.332681  0.289902   
4997     0.276549  0.458198  0.048136  0.070570  0.476522  0.273973  0.319218   
4998     0.263274  0.091205  0.072542  0.092405  0.283478  0.232877  0.078176   
4999     0.236726  0.454940  0.276949  0.299051  0.274783  0.326810  0.237785   

      Proximity_to_Industrial_Areas  Population_Density  Air Quality  
0                          0.163090            0.170351            2  
1                          0.150215            0.550065            2  
2                          0.115880            0.560468            2  
3                          0.369099            0.472042            0  
4                          0.437768            0.149545            0  
...                             ...                 ...          ...  
4995                       0.012876            0.750325            1  
4996                       0.137339            0.677503            2  
4997                       0.304721            0.248375            2  
4998                       0.390558            0.068921            0  
4999                       0.248927            0.355007            2  

[5000 rows x 10 columns]

In [14]:
# test-train split function algorithm
def data_splitting_python(data :carr.MutableSequence[float], target_var :str, test_perc :float, train_perc :float, 
                        print_stats :bool = False ) -> carr.Iterable[carr.MutableSequence[float],4]:
    """
    Function that creates a split between train and test data 

    :param data: dataframe
    :type data: carr.MutableSequence[float] 
    :param target_var: y-variable (target variable) 
    :type target_var: string
    :param test_perc: test percentage (in decimal representation)
    :type test_perc: float
    :param train_perc: train percentage (in decimal representation)
    :type train_perc: float
    :param print_stats: show the data length and data of train and test data
    :type print_stats: bool 
    :return: tuple of four consisting of train and test data 
    :rtype: tuple 
    :raises ValueError: N/A

    :example:
    >>> X_train, Y_train, x_test, y_test = data_splitting_python(dataframe,"target_variable",test_perc,train_perc)
    """
    
    
    length = len(data)
    test_len = int(length * test_perc)
    train_len = int(length * train_perc)
    random_df = data.sample(n = length).reset_index(drop = True)
    
    
    train_data = random_df.iloc[:train_len,:]
    test_data = random_df.iloc[train_len:length,:]

    
    y_train = test_data.drop(columns= target_var)
    y_test =  test_data.loc[:,target_var]

    x_train = train_data.drop(columns= target_var)
    x_test =  train_data.loc[:,target_var]

    
    
    if print_stats:
        print("test length: ", test_len)
        print("test data:\n",test_data)
        print("train length: ", train_len)
        print("train data:\n",train_data)

    
        
    return x_train, x_test, y_train, y_test



X_train, Y_train, x_test, y_test = data_splitting_python(df_mean_norm,"Air Quality",.30,.70)

# in this neural netwoek, we will use the mean normalized values for x train values
X_train


Temperature  Humidity     PM2.5      PM10       NO2       SO2        CO  \
0       -0.138233 -1.629905 -0.698125 -0.658826 -1.327895 -0.831788 -1.099496   
1        0.501585  0.973543 -0.343812  0.054175  1.718638  0.353344  0.970000   
2       -1.194677 -0.280903 -0.694052 -0.680764 -0.125020 -0.342921  0.255749   
3        1.617546  0.368384  2.458113  1.626433  0.853018  2.575466  3.625548   
4        2.599592  0.935721  1.452190  1.304669  1.460076  1.153308  1.958963   
...           ...       ...       ...       ...       ...       ...       ...   
3495     1.796100 -0.646520 -0.555585 -0.267590 -0.181229 -0.150337  0.072608   
3496    -0.971485  0.229701 -0.734778 -0.885524 -0.473517 -1.039186 -1.172752   
3497    -1.060762 -0.117005 -0.755141 -0.837990 -0.406066 -0.994743 -0.806470   
3498     0.159356  1.200478  0.108243 -0.073800 -0.979399  0.071875  0.383948   
3499     0.278392 -0.236776  0.759854  0.357657  0.470796 -0.105894  0.090922   

      Proximity_to_Industrial_Areas  Population_Density  
0                          0.602225           -1.259697  
1                         -1.502488            2.812208  
2                         -0.727068           -0.441388  
3                         -1.364020            2.013538  
4                         -0.893229            0.390014  
...                             ...                 ...  
3495                      -0.699374           -0.749072  
3496                       0.629918           -1.947076  
3497                       1.183790           -0.925827  
3498                      -0.450132            1.195230  
3499                      -0.616293           -0.762165  

[3500 rows x 9 columns]

In [15]:
# transforming from dataframe into array type 
input_matrix = np.array(X_train)
input_T = np.array(input_matrix).T

input_T

array([[-0.13823342,  0.50158456, -1.19467706, ..., -1.06076167,
         0.15935634,  0.27839224],
       [-1.62990481,  0.97354338, -0.2809026 , ..., -0.11700514,
         1.20047833, -0.23677636],
       [-0.6981249 , -0.34381169, -0.69405234, ..., -0.75514082,
         0.10824309,  0.7598536 ],
       ...,
       [-1.09949575,  0.97000024,  0.25574941, ..., -0.80646977,
         0.38394828,  0.0909223 ],
       [ 0.60222484, -1.5024881 , -0.72706755, ...,  1.18379026,
        -0.45013163, -0.61629318],
       [-1.2596966 ,  2.81220763, -0.44138787, ..., -0.92582664,
         1.19522958, -0.76216489]])

In [16]:
test_matrix = np.array(Y_train, dtype= int)
pred_T = test_matrix.T


pred_T

array([0, 1, 2, ..., 0, 2, 2])

# IV. Creating functions for neural network algorithm

In [17]:
# create activation functions

def softplus(x :carr.MutableSequence[float]) -> carr.MutableSequence[float]:
    """
    Function that serves as a softmax activation function

    :param x: dataframe
    :type data: carr.MutableSequence[float]  
    :return: array of transformed data by the softplus algorithm
    :rtype: np.array 
    :raises ValueError: N/A

    :example:
    >>> softplus([0.1,0.3,0.3,0.5])
    array([0.74439666, 0.85435524, 0.85435524, 0.97407698])
    """
    return np.log(1 + np.exp(x)) # log(1+e^(x))

def ReLU(x :carr.Iterable[float]) -> carr.Iterable[float]:
    """
    Function that serves as the ReLU activation algorithm 

    :param x: dataframe
    :type data: carr.MutableSequence[float]  
    :return: array of transformed data by the ReLU algorithm
    :rtype: np.array 
    :raises ValueError: N/A

    :example:
    >>> ReLU([0.1,-0.3,0.3,-0.5,-0.5,-0.6])
    array([0.1, 0. , 0.3, 0. , 0. , 0. ])
    """
    return np.maximum(0,x) 

def deriv_softplus(x :carr.Iterable[float]) -> carr.Iterable[float]:
    """
    Function that serves for the backpropogation, the derivative of softplus algorithm

    :param x: dataframe
    :type data: carr.MutableSequence[float]  
    :return: array of transformed data by the derivative of softplus, True means 1 and False represents 0
    :rtype: np.array 
    :raises ValueError: N/A

    :example:
    >>> a= softplus([0.1,0.3,0.3,0.5])
    >>> deriv_softplus(a)
    array([0.67795654, 0.70147996, 0.70147996, 0.72593138])
    """
    return  1 / (1 + np.exp(-x)) # 1 / (1 + e^(-x))

def deriv_ReLU(x :carr.Iterable[float]) -> carr.Iterable[float]:
    """
    Function that serves for the backpropogation, the derivative of ReLU algorithm

    :param x: dataframe
    :type data: carr.MutableSequence[float]  
    :return: array of transformed data by the derivative of ReLU, True means 1 and False represents 0
    :rtype: np.array 
    :raises ValueError: N/A

    :example:
    >>> a= ReLU([0.1,-0.3,0.3,-0.5,-0.5,-0.6])
    >>> deriv_ReLU(a)
    array([ True, False,  True, False, False, False])
    """
    return x > 0

# create classification activation function
def softmax(x : carr.MutableSequence[float]) -> carr.MutableSequence[float]:
    """
    Function that serves for classification which is the softmax function

    :param x: dataframe
    :type data: carr.MutableSequence[float]  
    :return: array of transformed data that shows a sequence of floats representing percentages of possible outputs
    :rtype: np.array 
    :raises ValueError: N/A

    : NOTE:
    on the summation of exponents, before adding all the exponents, 
    the array will be first set a boundary of -1 and 1 with values in between having no changes, 
    values that excede each boundary will be converted to its respective nearest boundary
    

    :example:
    >>> softmax([0.1,0.4,0.5])
    array([0.36839031, 0.4972749 , 0.54957376])
    """
    return np.exp(x) / np.sum(np.clip(np.exp(x),a_min=-1,a_max=1))

In [18]:
softmax([0.1,0.4,0.5])

array([0.36839031, 0.4972749 , 0.54957376])

In [19]:
# make bias and weight functions
def weight_bias_creator(num_input :int , num_activation :int, 
                        num_hidden_layers :int, num_classifers :int, minmax: carr.Iterable[int,int]  = [-.5,.5]) -> carr.Iterable[float]:

        # create neural map
        neural_map :carr.Iterable[float] = list()


        # initial hidden layer weight
        weight_matrix :carr.Iterable[float] = list()
        initial_hidden =  (minmax[1] - minmax[0]) * np.random.random_sample(size= (num_activation, num_input)) +  minmax[0]
        weight_matrix.append(initial_hidden)
        # middle hidden layers if hidden layers are more than 1 (num_hidden_layers > 1)
        if num_hidden_layers > 1:
                for i in range(num_hidden_layers - 1):
                        weight_matrix.append( (minmax[1] - minmax[0]) * np.random.random_sample(size= (num_activation, num_activation)) +  minmax[0])
        # classification weights
        classification_layer = (minmax[1] - minmax[0]) * np.random.random_sample(size= (num_classifers, num_activation)) +  minmax[0]
        weight_matrix.append(classification_layer)
        neural_map.append(weight_matrix)

        
        #biases from initial until hidden layer before the classificarion
        bias_matrix :carr.Iterable[float] = list()
        for i in range(num_hidden_layers):
                bias_matrix.append( (minmax[1] - minmax[0]) * np.random.random_sample(size= (num_activation,1)) +  minmax[0])
        #classification layer bias
        bias_matrix.append((minmax[1] - minmax[0]) * np.random.random_sample(size= (num_classifers, 1)) +  minmax[0])
        neural_map.append(bias_matrix)

        return neural_map


array_map = weight_bias_creator(len(X_train.columns),8,1,4) 


In [20]:
array_map

[[array([[-0.27536408,  0.09033949, -0.29105895, -0.47202338, -0.17939008,
           0.41778438, -0.22229508, -0.0005551 , -0.34009167],
         [-0.08430896,  0.45669941, -0.1636033 ,  0.13645186, -0.09125918,
          -0.06384054,  0.15452717,  0.40115922, -0.31352217],
         [ 0.28299084, -0.48314022, -0.17549502,  0.06143687,  0.32900341,
          -0.22998858,  0.0258297 , -0.29270315, -0.36229244],
         [ 0.21800585,  0.29093063,  0.44514767,  0.45141797,  0.47275844,
          -0.28008869,  0.38117684, -0.25321592,  0.4704878 ],
         [-0.28432586,  0.39503496,  0.23242125, -0.29426457, -0.25628222,
          -0.09525547, -0.10911396,  0.02414618, -0.08668152],
         [-0.44109252, -0.22837609, -0.38263704, -0.48800089, -0.37444554,
           0.04146693,  0.38988039, -0.4191422 , -0.42482626],
         [ 0.1388665 , -0.28991607, -0.07826074, -0.15386762,  0.02336886,
           0.45116438,  0.40535571, -0.19450401, -0.0108558 ],
         [ 0.22792063, -0.41592563

In [21]:
# feed forward

def feed_forward (array_map: carr.MutableSequence[float], input_matrix: carr.MutableSequence[float]) -> carr.MutableSequence[float]:
    # initialize arrays
    initial_data = input_matrix
    array_edge_result :carr.MutableSequence[float] = list()
    array_activation_result :carr.MutableSequence[float] = list()
    len_layers = len(array_map[0]) # checking for last layer
    
    
    # algorithm for 
    for i,j in enumerate(array_map[0]):

        # last layer checking to put softmax rather than ReLU
        if i == len_layers-1:
            weight_temp = array_map[0][i].dot(initial_data) + array_map[1][i]
            array_edge_result.append(weight_temp)
            activation = softmax(weight_temp)
            array_activation_result.append(activation)
            continue

        # creating edge values and activation values and append
        weight_temp = array_map[0][i].dot(initial_data) + array_map[1][i]
        array_edge_result.append(weight_temp)
        activation = ReLU(weight_temp)
        array_activation_result.append(activation)
        initial_data = activation

    # combining the arrays of edges and activation functions to crete a edge-activation map
    array_map_combined = [array_edge_result,array_activation_result]


    return array_map_combined
        
edge_activation_map = feed_forward(array_map,input_T)



In [22]:
edge_activation_map

[[array([[ 1.44261952, -0.83312766,  1.27419519, ...,  1.52203518,
           0.25646409,  0.09703425],
         [-0.38521799, -1.36569116, -0.40509817, ...,  0.46856345,
          -0.22186742, -0.55527494],
         [ 0.80597439, -0.36512568,  0.26413343, ..., -0.12988952,
          -1.21908566,  0.68936945],
         ...,
         [ 1.16620433, -1.32653724,  1.64102928, ...,  0.71358089,
          -0.32197687, -0.26956753],
         [-0.19587284,  0.8106951 ,  0.31707684, ..., -0.7805045 ,
           0.06695973,  0.27126473],
         [ 2.2155538 , -2.48047298,  0.09507518, ...,  1.10924631,
          -1.31573354, -0.56775799]]),
  array([[ 0.52141799, -0.55480367, -0.55676087, ...,  0.11519371,
          -0.43603526, -0.52519844],
         [ 0.57550846, -0.06978213,  0.50434285, ...,  0.69247836,
           0.40470393,  0.35626259],
         [-1.40123408,  0.42995709, -1.17306405, ..., -0.97567643,
          -0.03803776, -0.23093555],
         [-0.03629496,  0.52510069,  0.17971336,

In [23]:
# onehot encoding
def one_hot(Y : carr.MutableSequence[float]) -> carr.MutableSequence[float]:
    one_hot_Y = np.zeros((Y.size, Y.max() + 1))
    one_hot_Y[np.arange(Y.size), Y] = 1
    one_hot_Y = one_hot_Y.T
    return one_hot_Y



In [24]:
one_hot(pred_T)

array([[1., 0., 0., ..., 1., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 1., 1.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [25]:
# backprop

def back_propogation(weight_map :carr.MutableSequence[float], activation_map :carr.MutableSequence[float],
                    X :carr.MutableSequence[float],Y : carr.MutableSequence[float]) -> carr.MutableSequence[float]:
    # encoding y value training 
    one_hot_y = one_hot(Y)

    # create necessary variables 
    len_hidden :int = len(activation_map[1]) - 1 # get final index
    weight_adj_data : carr.MutableSequence[float] = list()
    bias_adj_data : carr.MutableSequence[float] = list()
    
    # last layer
    dE = activation_map[1][len_hidden] - one_hot_y
    dW = (1/m) * (dE.dot(activation_map[1][len_hidden-1].T))
    weight_adj_data.append(dW)
    dB = (1/m) * (np.sum(dE))
    bias_adj_data.append(dB)
    
    # middle layers
    dR = weight_map[0][len_hidden].T.dot(dE) * deriv_ReLU(activation_map[0][len_hidden-1])
    index = len_hidden - 1
    while index >= 1:
        dW = (1/m) * (dR.dot(activation_map[1][index-1].T))
        weight_adj_data.append(dW)
        dB = (1/m) * (np.sum(dR))
        bias_adj_data.append(dB)
        dR_new = weight_map[0][index].T.dot(dR) * deriv_ReLU(activation_map[0][index-1])
        dR = dR_new
        index -=1
    
    #first layer 
    dW = (1/m) * (dR.dot(X.T))
    weight_adj_data.append(dW)
    dB = (1/m) * (np.sum(dR))
    bias_adj_data.append(dB)
    
    # reverse the order of both weight and bias for easier updating of values
    array_map_combined = [weight_adj_data[::-1],bias_adj_data[::-1]]


    return array_map_combined


adj_matrix = back_propogation(array_map,edge_activation_map,input_T,pred_T)

In [26]:
adj_matrix

[[array([[ 0.05567397,  0.04773877,  0.02820444,  0.03882337,  0.05709792,
           0.05474098,  0.06736031, -0.07539285,  0.046298  ],
         [-0.02026831,  0.01187191, -0.01396881, -0.01672264, -0.02024749,
          -0.01882898, -0.02043634,  0.03571754, -0.03142508],
         [-0.00730958,  0.00251598,  0.00164997,  0.00057108, -0.00630648,
           0.00093119, -0.00523684,  0.01579486,  0.00107054],
         [-0.01695207, -0.02260617, -0.03210613, -0.03332094, -0.02434418,
          -0.00988251, -0.02215991,  0.04258333, -0.02585838],
         [ 0.00151589, -0.04899637, -0.00638217, -0.00832141, -0.0073452 ,
          -0.00981744, -0.01771862,  0.03430912, -0.00957548],
         [-0.05306083, -0.04893519, -0.04674001, -0.0538227 , -0.05508621,
          -0.04500654, -0.05463997,  0.03201636, -0.05706463],
         [ 0.02322485,  0.00265018, -0.00505654,  0.0005301 ,  0.01809386,
           0.03585343,  0.02887316, -0.05770545,  0.01673689],
         [ 0.09533058,  0.06989905

In [27]:
# update parameters

def update_params(array_map :carr.MutableSequence[float], adj_matrix :carr.MutableSequence[float], alpha :float) -> carr.MutableSequence[float]:
    
    # initialize main and sub arrays
    len_arr = len(array_map[0]) # know the length of neural network
    new_array_map :carr.MutableSequence[float] = list()
    new_bias :carr.MutableSequence[float] = list()
    new_weight :carr.MutableSequence[float] = list()


    # updating values w/r to the learning rate 
    for index in range(len_arr):
        new_weight.append(array_map[0][index] - alpha * adj_matrix[0][index])
        new_bias.append(array_map[1][index] - alpha * adj_matrix[1][index])
    

    # combine sub arrays into the main array 
    new_array_map = [new_weight,new_bias]

    return new_array_map







new_array_map = update_params(array_map,adj_matrix,0.01)

In [28]:
new_array_map

[[array([[-2.75920823e-01,  8.98620996e-02, -2.91340997e-01,
          -4.72411610e-01, -1.79961055e-01,  4.17236966e-01,
          -2.22968681e-01,  1.98824182e-04, -3.40554652e-01],
         [-8.41062727e-02,  4.56580692e-01, -1.63463611e-01,
           1.36619089e-01, -9.10567064e-02, -6.36522483e-02,
           1.54731537e-01,  4.00802048e-01, -3.13207923e-01],
         [ 2.83063932e-01, -4.83165382e-01, -1.75511522e-01,
           6.14311564e-02,  3.29066472e-01, -2.29997889e-01,
           2.58820703e-02, -2.92861102e-01, -3.62303146e-01],
         [ 2.18175371e-01,  2.91156693e-01,  4.45468730e-01,
           4.51751176e-01,  4.73001884e-01, -2.79989860e-01,
           3.81398444e-01, -2.53641753e-01,  4.70746386e-01],
         [-2.84341024e-01,  3.95524928e-01,  2.32485075e-01,
          -2.94181352e-01, -2.56208771e-01, -9.51572996e-02,
          -1.08936771e-01,  2.38030880e-02, -8.65857645e-02],
         [-4.40561911e-01, -2.27886733e-01, -3.82169639e-01,
          -4.874626

# V.  Create neural network and accuracy models 

In [29]:
def get_predictions(A2):
    return np.argmax(A2, 0)

def get_accuracy(predictions, Y):
    print(predictions, Y)
    return np.sum(predictions == Y) / Y.size

def gradient_descent(X :carr.MutableSequence[float], Y :carr.MutableSequence[float], 
                     alpha :float, iterations :int) -> carr.MutableSequence[float]:
    # initialize the creation of weights and biases w/r to the number of inputs, layers, and outputs
    temp_array = weight_bias_creator(len(X_train.columns),10,3,4) 
    len_feed :int = len(temp_array[0])

    # gradient descent algorithm 
    for i in range(iterations):
        edge_activation_map = feed_forward(temp_array,X)
        adj_matrix = back_propogation(temp_array,edge_activation_map,X,Y)
        new_array_map = update_params(temp_array,adj_matrix,alpha)
        temp_array = new_array_map
        if i % 10 == 0: # per 10 iterations, show accuracy
            print("Iteration: ", i)
            predictions = get_predictions(edge_activation_map[1][len_feed-1])
            print(get_accuracy(predictions, Y))
    return temp_array

In [30]:
weight_bias_model_matrix : carr.MutableSequence[float] = gradient_descent(input_T, pred_T, 0.1, 2000)

Iteration:  0
[3 2 3 ... 2 3 3] [0 1 2 ... 0 2 2]
0.18628571428571428
Iteration:  10
[3 2 3 ... 3 3 3] [0 1 2 ... 0 2 2]
0.16914285714285715
Iteration:  20
[0 2 2 ... 0 2 2] [0 1 2 ... 0 2 2]
0.5911428571428572
Iteration:  30
[0 2 0 ... 0 2 2] [0 1 2 ... 0 2 2]
0.5057142857142857
Iteration:  40
[3 2 3 ... 3 2 2] [0 1 2 ... 0 2 2]
0.33057142857142857
Iteration:  50
[2 2 2 ... 2 2 2] [0 1 2 ... 0 2 2]
0.3191428571428571
Iteration:  60
[0 2 2 ... 0 2 2] [0 1 2 ... 0 2 2]
0.7231428571428572
Iteration:  70
[0 1 2 ... 0 2 2] [0 1 2 ... 0 2 2]
0.8368571428571429
Iteration:  80
[0 1 2 ... 0 2 2] [0 1 2 ... 0 2 2]
0.8305714285714285
Iteration:  90
[0 1 2 ... 0 2 2] [0 1 2 ... 0 2 2]
0.8705714285714286
Iteration:  100
[0 3 2 ... 0 2 2] [0 1 2 ... 0 2 2]
0.8957142857142857
Iteration:  110
[0 3 2 ... 0 2 2] [0 1 2 ... 0 2 2]
0.9025714285714286
Iteration:  120
[0 3 2 ... 0 2 2] [0 1 2 ... 0 2 2]
0.908
Iteration:  130
[0 3 2 ... 0 2 2] [0 1 2 ... 0 2 2]
0.9134285714285715
Iteration:  140
[0 3 2 ... 

In [31]:
# shows the optimal values for weigths and biases 
weight_bias_model_matrix

[[array([[-0.21148351, -0.05153229, -0.00532342,  0.06709167, -0.1387631 ,
           0.26300967, -0.54934214,  0.63504926, -0.26449309],
         [-0.12423167, -0.10759856,  0.23810584, -0.21440001, -0.30620496,
          -0.19153205, -0.66973745,  0.20107774, -0.05295875],
         [-0.12563739,  0.07163267, -0.00524251,  0.029431  ,  0.29619616,
           0.20113977,  0.19821596,  0.47930232, -0.20003752],
         [ 0.19447375,  0.17337434, -0.51588244,  0.64120163,  0.28397825,
           0.16897462,  0.51665972,  0.02711035,  0.14618566],
         [ 0.22678773,  0.07536397, -0.28272838,  0.39692992,  0.31668091,
           0.3328099 ,  0.81782617, -0.27416493,  0.18395634],
         [-0.03729937, -0.06021315,  0.40081475, -0.3708676 , -0.16286366,
          -0.1580789 , -0.14162524,  0.03338317,  0.18678789],
         [-0.19282001,  0.17330216, -0.25714419, -0.22475111,  0.20452231,
          -0.10756961, -0.56335362,  0.23922003,  0.11076944],
         [ 0.22960178,  0.01602514

# VI. Checking for accuracy of the model

In [34]:
# create prediction alagorithm to find accuracy of the model
def make_predictions(X :carr.MutableSequence[float], 
                     weight_bias_map :carr.MutableSequence[float]) -> carr.MutableSequence[float]:
    prediction_map = feed_forward(weight_bias_model_matrix,X)
    len_pred = len(prediction_map[0])
    predictions = get_predictions(prediction_map[1][len_pred-1])
    return predictions

In [35]:
dev_predictions = make_predictions(np.array(x_test).T,weight_bias_model_matrix)
get_accuracy(dev_predictions, np.array(y_test).T)

[0 2 3 ... 1 0 0] [0 2 3 ... 1 0 0]


np.float64(0.942)

In [37]:
# creeating table to see the right and wrong values more clearly
x_test["y_obs"] = y_test
x_test["y_pred"] = dev_predictions.T

In [39]:
# a function comparing test y value to y value generated by neural network
def correct(x : carr.MutableSequence[float])-> carr.MutableSequence[float]:
    if x["y_obs"] == x["y_pred"]:
        return 1
    return 0

In [40]:
x_test["correct"] = x_test.apply(correct,axis=1)

In [41]:
x_test

Temperature  Humidity     PM2.5      PM10       NO2       SO2        CO  \
3500    -0.867328 -0.860847 -0.718488 -0.666139 -1.653908 -1.009558 -0.952983   
3501    -0.093595  0.154056 -0.331594 -0.552790  0.021123 -0.017010 -0.055591   
3502     1.498510 -0.274599 -0.237925  0.032236  0.718116  1.553290  1.171456   
3503     0.382549 -0.545660  0.698765  0.836648  0.156025  0.264459  0.274064   
3504     0.546223  0.834861 -0.404900  0.072457  0.808051  2.619909  1.885706   
...           ...       ...       ...       ...       ...       ...       ...   
4995    -0.197751 -1.560564  0.922756  0.628232 -1.653908 -1.054000 -0.843098   
4996    -0.391185  0.721393 -0.050587  0.006642 -0.428549  0.412601  0.090922   
4997     2.495436  1.320250 -0.812157 -0.483318  3.236284  1.405149  1.574366   
4998    -1.879134 -1.661424 -0.380465 -0.465036 -0.158746 -1.261398 -1.227695   
4999    -0.153113 -1.718157 -0.738851 -1.020811 -0.664628 -0.609576 -0.861412   

      Proximity_to_Industrial_Areas  Population_Density  y_obs  y_pred  \
3500                       0.879161           -1.030570      0       0   
3501                       0.020659           -0.068239      2       2   
3502                      -1.087084            0.913731      3       3   
3503                      -0.920923            0.206713      2       2   
3504                       0.962242            0.285270      3       3   
...                             ...                 ...    ...     ...   
4995                       3.011567            0.520943      0       0   
4996                      -0.920923           -1.024024      2       2   
4997                      -1.640956            0.586408      1       1   
4998                       0.491450            0.115062      0       0   
4999                       0.463757           -0.454481      0       0   

      correct  
3500        1  
3501        1  
3502        1  
3503        1  
3504        1  
...       ...  
4995        1  
4996        1  
4997        1  
4998        1  
4999        1  

[1500 rows x 12 columns]

In [42]:
# show number of correct and wrong
x_test["correct"].value_counts()

correct
1    1413
0      87
Name: count, dtype: int64

In [43]:
# manual computation of accuracy for double checking
x_test["correct"].value_counts()[1] / (x_test["correct"].value_counts()[0] + x_test["correct"].value_counts()[1] )

np.float64(0.942)